version: "3"
services:
    api:
        image: meu_app
        container_name: api
        build:
            context: ../
            dockerfile: ./src/AutoService.Api/Dockerfile/
        ports:
            - "8080:8080"
            - "8081:8081"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
            - db
        networks: 
            - default
    db:
        image: mysql:latest
        container_name: mysql_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root1234
            MYSQL_DATABASE: auto_service_db
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        expose:
            - "3306"
        networks: 
            - default
volumes:
  mysql_data:
    driver: local

networks:
    default:
        name: network_default
